# Generated by Django 4.2.6 on 2023-10-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='country',
            new_name='city',
        ),
    ]
